namespace FastGeography.Server.Services.Ai;

/// <summary>
/// Tries chat clients in order until one returns a non-empty completion.
/// </summary>
public sealed class FallbackChatClient : IChatCompletionClient
{
    private readonly IReadOnlyList<(string Name, IChatCompletionClient Client)> _clients;
    private readonly ILogger<FallbackChatClient> _logger;

    public FallbackChatClient(
        IReadOnlyList<(string Name, IChatCompletionClient Client)> clients,
        ILogger<FallbackChatClient> logger)
    {
        _clients = clients;
        _logger = logger;
    }

    public async Task<string?> CompleteAsync(string systemPrompt, string userPrompt, CancellationToken ct = default)
    {
        foreach (var (name, client) in _clients)
        {
            var story = await client.CompleteAsync(systemPrompt, userPrompt, ct);
            if (!string.IsNullOrWhiteSpace(story))
            {
                _logger.LogInformation("Destination story generated by {Provider}", name);
                return story;
            }

            _logger.LogInformation("Provider {Provider} returned no story — trying next", name);
        }

        return null;
    }
}
